Kullanıcının ayarlarının okunmama problemi giderildi.
ssg/cinali pull request #2
Opened 2016-11-30 12:16 UTC by firateski

'Settings' sınıfının 'ReadFromRegistry()' fonksiyonunun çağrılmamasından
kaynaklanan bir problem giderildi ve 'Settings' sınıfına 'NoLimitCheckBox' nesnesinin değerinin kayıt defterine eklenmesi sağlandı.

Not: Program açılışında ayarların okunup nesnelere atanması sırasında nesnelerin 'changed' tetikleyicilerinin çağırdığı 'updateSpeedLimit()' fonksiyonu 'Settings' sınıfındaki 'NoLimit' ve 'SpeedLimit' özelliklerine müdahele ediyor bu da ayarların yanlış ayarlanmasına neden oluyordu. Bu nedenle 'tempNoLimitProperty' isminde değişken eklenerek bu problem giderildi.

2016-11-30 23:11 UTC, ssg requested changes

2016-12-01 10:26 UTC, firateski commented on Settings.cs
> +                if (value) SpeedLimit = 0;
Evet, dikkatsizliğin kurbanı olmuşum 😳 Şimdi hemen düzeltiyorum.

2016-12-01 21:38 UTC, ssg requested changes

2016-12-01 21:38 UTC, ssg commented on Settings.cs
> +        public int SpeedLimit { get { return speedLimit; } set { speedLimit = value; } }
kontrol degistigine gore bu da dogrudan get; set; olabilir.

2016-12-01 22:08 UTC, firateski commented on Settings.cs
> +        public int SpeedLimit { get { return speedLimit; } set { speedLimit = value; } }
Yine güzel bir yerden yakaladınız 😬 Hemen değiştiriyorum 👍

2016-12-01 22:13 UTC, merged